-- Images extracted from the workbook's SKU rows; no inferred matches.
begin;
insert into public.product_images(product_id,url,alt_text,is_primary) select id,'/catalog/DS-W-2562.png','DS-W-2562',true from public.products where sku='DS-W-2562' and not exists(select 1 from public.product_images i where i.product_id=products.id and i.url='/catalog/DS-W-2562.png');
insert into public.product_images(product_id,url,alt_text,is_primary) select id,'/catalog/DS-C-334.png','DS-C-334',true from public.products where sku='DS-C-334' and not exists(select 1 from public.product_images i where i.product_id=products.id and i.url='/catalog/DS-C-334.png');
insert into public.product_images(product_id,url,alt_text,is_primary) select id,'/catalog/DS-W-2562.png','DS-W-2562',true from public.products where sku='DS-W-2562' and not exists(select 1 from public.product_images i where i.product_id=products.id and i.url='/catalog/DS-W-2562.png');
insert into public.product_images(product_id,url,alt_text,is_primary) select id,'/catalog/DS-C-161.png','DS-C-161',true from public.products where sku='DS-C-161' and not exists(select 1 from public.product_images i where i.product_id=products.id and i.url='/catalog/DS-C-161.png');
insert into public.product_images(product_id,url,alt_text,is_primary) select id,'/catalog/DS-C-118D.png','DS-C-118D',true from public.products where sku='DS-C-118D' and not exists(select 1 from public.product_images i where i.product_id=products.id and i.url='/catalog/DS-C-118D.png');
insert into public.product_images(product_id,url,alt_text,is_primary) select id,'/catalog/DS-C-308A.png','DS-C-308A',true from public.products where sku='DS-C-308A' and not exists(select 1 from public.product_images i where i.product_id=products.id and i.url='/catalog/DS-C-308A.png');
insert into public.product_images(product_id,url,alt_text,is_primary) select id,'/catalog/DS-C-119A.png','DS-C-119A',true from public.products where sku='DS-C-119A' and not exists(select 1 from public.product_images i where i.product_id=products.id and i.url='/catalog/DS-C-119A.png');
insert into public.product_images(product_id,url,alt_text,is_primary) select id,'/catalog/DS-W-2549.png','DS-W-2549',true from public.products where sku='DS-W-2549' and not exists(select 1 from public.product_images i where i.product_id=products.id and i.url='/catalog/DS-W-2549.png');
insert into public.product_images(product_id,url,alt_text,is_primary) select id,'/catalog/DS-W-2551.png','DS-W-2551',true from public.products where sku='DS-W-2551' and not exists(select 1 from public.product_images i where i.product_id=products.id and i.url='/catalog/DS-W-2551.png');
insert into public.product_images(product_id,url,alt_text,is_primary) select id,'/catalog/DS-C-147.png','DS-C-147',true from public.products where sku='DS-C-147' and not exists(select 1 from public.product_images i where i.product_id=products.id and i.url='/catalog/DS-C-147.png');
insert into public.product_images(product_id,url,alt_text,is_primary) select id,'/catalog/DS-C-312.png','DS-C-312',true from public.products where sku='DS-C-312' and not exists(select 1 from public.product_images i where i.product_id=products.id and i.url='/catalog/DS-C-312.png');
insert into public.product_images(product_id,url,alt_text,is_primary) select id,'/catalog/DS-W-2569.png','DS-W-2569',true from public.products where sku='DS-W-2569' and not exists(select 1 from public.product_images i where i.product_id=products.id and i.url='/catalog/DS-W-2569.png');
insert into public.product_images(product_id,url,alt_text,is_primary) select id,'/catalog/DS-W-2582.png','DS-W-2582',true from public.products where sku='DS-W-2582' and not exists(select 1 from public.product_images i where i.product_id=products.id and i.url='/catalog/DS-W-2582.png');
insert into public.product_images(product_id,url,alt_text,is_primary) select id,'/catalog/DS-C-137A.png','DS-C-137A',true from public.products where sku='DS-C-137A' and not exists(select 1 from public.product_images i where i.product_id=products.id and i.url='/catalog/DS-C-137A.png');
insert into public.product_images(product_id,url,alt_text,is_primary) select id,'/catalog/DS-W-2583.png','DS-W-2583',true from public.products where sku='DS-W-2583' and not exists(select 1 from public.product_images i where i.product_id=products.id and i.url='/catalog/DS-W-2583.png');
commit;
